swiftmailer:
    #spool: { type: 'memory' }
    spool:
        type: file
        path: '%kernel.project_dir%/var/spool'
    disable_delivery: false
    host: '%env(MAILER_HOST)%'
    password: '%env(MAILER_PASSWORD)%'
    username: '%env(MAILER_USERNAME)%'
    transport: '%env(MAILER_TRANSPORT)%'
    encryption: '%env(MAILER_ENCRYPTION)%'
    port: '%env(MAILER_PORT)%'
