framework:
    default_locale: de
    translator:
        default_path: '%kernel.project_dir%/translations/custom'
        path:
            - '%kernel.project_dir%/translations'
        fallbacks:
            - de
