files:
  - source: /translations/messages+intl-icu.en.xlf
    translation: /translations/messages+intl-icu.%two_letters_code%.xlf
  - source: /translations/form.en.yml
    translation: /translations/form.%two_letters_code%.yml
