version: '3.8'

x-app-common: &jitsi_admin_app
  build: .
  environment:
    APACHE_DOCUMENT_ROOT: "public/"
    PHP_EXTENSION_XDEBUG: "1"
    PHP_INI_MEMORY_LIMIT: "1G"
    PHP_EXTENSION_LDAP: 1
    PHP_EXTENSION_INTL: 1
    DATABASE_URL: mysql://jitsiadmin:${JITSI_ADMIN_PW}@${RANDOMTAG}db-ja:3306/jitsiadmin
    MERCURE_URL: http://${RANDOMTAG}websocket-ja:3000/.well-known/mercure
    MERCURE_PUBLIC_URL: ${HTTP_METHOD}://${PUBLIC_URL}
    MERCURE_JWT_SECRET: ${MERCURE_JWT_SECRET}
    WEBSOCKET_SECRET: ${MERCURE_JWT_SECRET}
    MAILER_DSN: ${MAILER_DSN}
    registerEmailAdress: ${registerEmailAdress}


services:
  websocket-ja:
    build: nodejs
    hostname: ${RANDOMTAG}websocket-ja
    restart: unless-stopped
    environment:
      WEBSOCKET_SECRET: '${MERCURE_JWT_SECRET}'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/healthz"]
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.websocket-ja-${RANDOMTAG}.rule=Host(`${PUBLIC_URL}`)&& PathPrefix(`/ws`)"
      - "traefik.http.routers.websocket-ja-${RANDOMTAG}.entrypoints=web"
      - "traefik.http.routers.websocket-ja-${RANDOMTAG}.tls=true"
      - "traefik.http.services.websocket-ja-${RANDOMTAG}.loadbalancer.server.port=3000"
      - "traefik.http.routers.websocket-ja-${RANDOMTAG}.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=http"
      - "traefik.http.routers.app-secure.middlewares=sslheader@docker"

    volumes:
      - caddy_config:/config
    networks:
      - default
      - jitsi-admin

  whiteboard-ja:
    build: https://github.com/H2-invent/materialWhitebophir.git
    restart: unless-stopped
    environment:
      AUTH_SECRET_KEY: '${MERCURE_JWT_SECRET}'
      PORT: 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whiteboard-ja-${RANDOMTAG}.rule=Host(`whiteboard.${PUBLIC_URL}`)"
      - "traefik.http.routers.whiteboard-ja-${RANDOMTAG}.entrypoints=web"
      - "traefik.http.routers.whiteboard-ja-${RANDOMTAG}.tls=true"
      - "traefik.http.services.whiteboard-ja-${RANDOMTAG}.loadbalancer.server.port=80"
      - "traefik.http.routers.whiteboard-ja-${RANDOMTAG}.tls.certresolver=letsencrypt"

    volumes:
      - wbo-boards:/opt/app/server-data

    networks:
      - default

  etherpad:
    #build: .
    image: etherpad/etherpad:latest
    restart: unless-stopped
    environment:
      AUTH_SECRET_KEY: MY_SECRET
      PAD_OPTIONS_SHOW_CHAT: false
      PAD_SHORTCUTS_ENABLED_ALT_C: false
      DEFAULT_PAD_TEXT: "Agenda\n\nTOP1\n\nTOP2\n\nTOP3\n\nTOP4\n\n\n\nNext Steps:\n Write here what to do next\n\n\n\n\nQuestions:\nWrite here any questions the team have\n\n"
    security_opt:
      - no-new-privileges:true
    volumes:
      - etherpad_data:/opt/etherpad-lite/var

    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.etherpad-ja-${RANDOMTAG}.tls=true"
      - "traefik.http.routers.etherpad-ja-${RANDOMTAG}.rule=Host(`meeting-notes.${PUBLIC_URL}`)"
      - "traefik.http.routers.etherpad-ja-${RANDOMTAG}.entrypoints=web"
      - "traefik.http.services.etherpad-ja-${RANDOMTAG}.loadbalancer.server.port=9001"
      - "traefik.http.routers.etherpad-ja-${RANDOMTAG}.tls.certresolver=letsencrypt"


  #Here is the Jitsi-Admin app
  app-ja:
    <<: *jitsi_admin_app
    hostname: ${RANDOMTAG}app-ja
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:80/health/check || exit 1
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 30s
    depends_on:
      db-ja:
        condition: service_healthy
    environment:
      APACHE_DOCUMENT_ROOT: "public/"
      PHP_EXTENSION_XDEBUG: "1"
      PHP_INI_MEMORY_LIMIT: "1G"
      PHP_EXTENSION_LDAP: 1
      PHP_EXTENSION_INTL: 1
      PHP_INI_UPLOAD_MAX_FILESIZE: 8M
      PHP_INI_POST_MAX_SIZE: 8M
      DATABASE_URL: mysql://jitsiadmin:${JITSI_ADMIN_PW}@${RANDOMTAG}db-ja:3306/jitsiadmin
      MAILER_TRANSPORT: smtp
      OAUTH_KEYCLOAK_CLIENT_ID: jitsiadmin
      OAUTH_KEYCLOAK_CLIENT_SECRET: ${OAUTH_KEYCLOAK_CLIENT_SECRET}
      OAUTH_KEYCLOAK_SERVER: ${HTTP_METHOD}://${PUBLIC_URL}/keycloak
      OAUTH_KEYCLOAK_REALM: jitsiadmin
      MERCURE_URL: http://${RANDOMTAG}websocket-ja:3000/.well-known/mercure
      MERCURE_PUBLIC_URL: ${HTTP_METHOD}://${PUBLIC_URL}
      MERCURE_JWT_SECRET: ${MERCURE_JWT_SECRET}
      WEBSOCKET_SECRET: ${MERCURE_JWT_SECRET}
      MAILER_DSN: ${MAILER_DSN}
      laF_version: ${GIT_VERSION}
      registerEmailAdress: ${registerEmailAdress}
      laF_baseUrl: ${HTTP_METHOD}://${PUBLIC_URL}
      VICH_BASE: ${HTTP_METHOD}://${PUBLIC_URL}
      LAF_WHITEBOARD_FUNCTION: 1
      WHITEBOARD_URL:  ${HTTP_METHOD}://whiteboard.${PUBLIC_URL}
      WHITEBOARD_SECRET: '${MERCURE_JWT_SECRET}'
      ETHERPAD_URL: ${HTTP_METHOD}://meeting-notes.${PUBLIC_URL}
      ETHERPAD_SECRET: MY_SECRET
      LAF_ETHERPAD_FUNCTION: 1
      SEND_REPORT_AFTER_MEETING: 1
      input_settings_allow_timezone: 1
      allowTimeZoneSwitch: 1
      CRON_USER_1: root
      CRON_SCHEDULE_1: "* * * * *"
      CRON_COMMAND_1: "php /var/www/html/bin/console cron:run"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-ja-${RANDOMTAG}.tls=true"
      - "traefik.http.routers.app-ja-${RANDOMTAG}.rule=Host(`${PUBLIC_URL}`)"
      - "traefik.http.routers.app-ja-${RANDOMTAG}.entrypoints=web"
      - "traefik.http.services.app-ja-${RANDOMTAG}.loadbalancer.server.port=80"
      - "traefik.http.routers.app-ja-${RANDOMTAG}.tls.certresolver=letsencrypt"
      - "traefik.http.services.app-ja-${RANDOMTAG}.loadbalancer.sticky=true"
      - "traefik.http.services.app-ja-${RANDOMTAG}.loadbalancer.sticky.cookie.name=jad"
      - "traefik.http.services.app-ja-${RANDOMTAG}.loadbalancer.sticky.cookie.secure=true"
    volumes:
      - theme_data:/var/www/html/theme
      - image_upload:/var/www/html/public/uploads/images
      - theme_assests_data:/var/www/html/public/theme

    networks:
      - default
      - jitsi-admin

  app-queu:
    <<: *jitsi_admin_app
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      app-ja:
        condition: service_healthy
    command: php /var/www/html/bin/console messenger:consume async --memory-limit=126m
    volumes:
      - theme_data:/var/www/html/theme
    networks:
      - default
      - jitsi-admin

  db-ja:
    image: mariadb:latest
    hostname: ${RANDOMTAG}db-ja
    environment:
      MARIADB_ROOT_PASSWORD: test
    healthcheck:
      test: [ "CMD", "mariadb-admin" ,"ping", "-h", "localhost","-ptest" ]
      timeout: 20s
      retries: 10
    volumes:
      - mariadb:/var/lib/mysql
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - jitsi-admin


  keycloak-ja:
    image: quay.io/keycloak/keycloak:22.0.3
    hostname: ${RANDOMTAG}keycloak-ja
    depends_on:
      db-ja:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PW}
      KC_DB: mariadb
      KC_DB_PASSWORD: ${KEYCLOAK_PW}
      KC_DB_URL: jdbc:mariadb://${RANDOMTAG}db-ja:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_HOSTNAME_URL: ${HTTP_METHOD}://${PUBLIC_URL}/keycloak
      KC_HOSTNAME_PATH: ${HTTP_METHOD}://${PUBLIC_URL}/keycloak
      KC_HOSTNAME_ADMIN_URL: ${HTTP_METHOD}://${PUBLIC_URL}/keycloak
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_PROXY: passthrough
    command:
      - start-dev
      - --import-realm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak-ja-${RANDOMTAG}.tls=true"
      - "traefik.http.routers.keycloak-ja-${RANDOMTAG}.rule=Host(`${PUBLIC_URL}`)&& PathPrefix(`/keycloak`)"
      - "traefik.http.routers.keycloak-ja-${RANDOMTAG}.entrypoints=web"
      - "traefik.http.services.keycloak-ja-${RANDOMTAG}.loadbalancer.server.port=8080"
      - "traefik.http.routers.keycloak-ja-${RANDOMTAG}.tls.certresolver=letsencrypt"

    volumes:
      - ./docker/keycloak/:/opt/keycloak/data/import
    networks:
      - default
      - jitsi-admin

volumes:
  mariadb:
  caddy_config:
  image_upload:
  wbo-boards:
  etherpad_data:
  theme_data:
  theme_assests_data:

networks:
  default:
    name: gateway

  jitsi-admin:
    internal: true
