version: '3.7'

services:
  traefik-ja:
    image: "traefik:v2.5"
    container_name: "traefik-ja"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entryPoints=traefik"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=api-auth"
      - "traefik.http.middlewares.api-auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/" # test:test

    ports:
      - "80:80"
      #- "443:443"
      - "8181:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./tools/certs:/tools/certs
      - ./tools/traefik/config.yml:/etc/traefik/dynamic_conf/conf.yml:ro

  mercure-ja:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      #SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'test'
      MERCURE_SUBSCRIBER_JWT_KEY: 'test'
      SERVER_NAME: ':3000'
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mercure-ja.rule=Host(`mercure.${PUBLIC_URL}`)"
      - "traefik.http.routers.mercure-ja.entrypoints=web"
      - "traefik.http.services.mercure-ja.loadbalancer.server.port=3000"
    #    ports:
    #      - "3000:3000"
    #      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
  app-ja:
    build: .
    depends_on:
      - db-ja
      - keycloak-ja
      - mercure-ja
      - traefik-ja
    command: [ "dockerRun.sh" ]

    environment:
      APACHE_DOCUMENT_ROOT: "public/"
      PHP_EXTENSION_XDEBUG: "1"
      PHP_INI_MEMORY_LIMIT: "1G"
      PHP_EXTENSION_LDAP: 1
      PHP_EXTENSION_INTL: 1
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: mysql://jitsiadmin:test@db-ja:3306/jitsiadmin
      MAILER_HOST: ""
      MAILER_PORT: 587
      MAILER_PASSWORD: ""
      MAILER_USERNAME: ""
      MAILER_ENCRYPTION: tls
      MAILER_TRANSPORT: smtp
      OAUTH_KEYCLOAK_CLIENT_ID: jitsiadmin
      OAUTH_KEYCLOAK_CLIENT_SECRET: wLR9qXB4tuBqdsp3WtQ7OwVuDkxiJT7m
      OAUTH_KEYCLOAK_SERVER: http://keycloak.${PUBLIC_URL}/auth
      OAUTH_KEYCLOAK_REALM: jitsiadmin
      MERCURE_URL: http://mercure-ja:3000/.well-known/mercure
      MERCURE_PUBLIC_URL: http://mercure.${PUBLIC_URL}/.well-known/mercure
      MERCURE_JWT_SECRET: test
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-ja.rule=Host(`${PUBLIC_URL}`)"
      - "traefik.http.routers.app-ja.entrypoints=web"
      - "traefik.http.services.app-ja.loadbalancer.server.port=80"
    #volumes:
    #  - ./:/var/www/html:rw

  db-ja:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: test
    volumes:
      - mariadb:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d


  keycloak-ja:
    image: jboss/keycloak:latest
    hostname: keycloak.${PUBLIC_URL}
    depends_on:
      - db-ja
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: test
      DB_VENDOR: mariadb
      DB_ADDR: db-ja
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: test
      DB_PORT: 3306
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak-ja.rule=Host(`keycloak.${PUBLIC_URL}`)"
      - "traefik.http.routers.keycloak-ja.entrypoints=web"
      - "traefik.http.services.keycloak-ja.loadbalancer.server.port=8080"
      # KC_HOSTNAME not required because of start-dev
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json



volumes:
  mariadb:
  caddy_data:
  caddy_config:
