COPY ca_certificate.pem client_certificate.pem client_key.pem /
RUN chown ${DDEV_UID}:${DDEV_GID} /ca_certificate.pem /client_certificate.pem /client_key.pem
RUN chmod 600 /ca_certificate.pem /client_certificate.pem /client_key.pem
