COPY ca_certificate.pem client_certificate.pem client_key.pem /
RUN chown h2invent:h2invent /ca_certificate.pem /client_certificate.pem /client_key.pem
RUN chmod 600 /ca_certificate.pem /client_certificate.pem /client_key.pem
