<?php

namespace App\Tests\callOut;

use App\Entity\CallerId;
use App\Entity\CalloutSession;
use App\Repository\RoomsRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class CalloutApiActionControllerUnauthorizedTest extends WebTestCase
{
    private $client;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->client = static::createClient(
            [],
            [
                'HTTP_AUTHORIZATION' => 'Bearer invalid',
            ]
        );
        $manager = self::getContainer()->get(EntityManagerInterface::class);
        $userRepo = self::getContainer()->get(UserRepository::class);
        $roomRepo = self::getContainer()->get(RoomsRepository::class);
        $room = $roomRepo->findOneBy(['name' => 'TestMeeting: 0']);
        $user = $userRepo->findOneBy(['email' => 'ldapUser@local.de']);

        $calloutSession1 = new CalloutSession();
        $calloutSession1->setUser($user)
            ->setRoom($room)
            ->setCreatedAt(new \DateTime())
            ->setInvitedFrom($room->getModerator())
            ->setState(1)
            ->setUid('ksdlfjlkfds')
            ->setLeftRetries(2);
        $manager->persist($calloutSession1);
        $callerUserId = new CallerId();
        $callerUserId->setCreatedAt(new \DateTime())
            ->setRoom($room)
            ->setUser($user)
            ->setCallerId('987654321');
        $manager->persist($callerUserId);
        $manager->flush();
    }

    public function testDialin(): void
    {
        $crawler = $this->client->request('GET', '/api/v1/call/out/dial/ksdlfjlkfds');
        $this->assertEquals(401, $this->client->getResponse()->getStatusCode());
    }

    public function testUnrecheable(): void
    {
        $crawler = $this->client->request('GET', '/api/v1/call/out/unreachable/ksdlfjlkfds');
        $this->assertEquals(401, $this->client->getResponse()->getStatusCode());
    }

    public function testBack(): void
    {
        $crawler = $this->client->request('GET', '/api/v1/call/out/back/ksdlfjlkfds');
        $this->assertEquals(401, $this->client->getResponse()->getStatusCode());
    }

    public function testError(): void
    {

        $crawler = $this->client->request('GET', '/api/v1/call/out/error/ksdlfjlkfds');
        $this->assertEquals(401, $this->client->getResponse()->getStatusCode());
    }
    public function testrefuse(): void
    {

        $crawler = $this->client->request('GET', '/api/v1/call/out/refuse/ksdlfjlkfds');
        $this->assertEquals(401, $this->client->getResponse()->getStatusCode());
    }

    public function testTimeout(): void
    {

        $crawler = $this->client->request('GET', '/api/v1/call/out/timeout/ksdlfjlkfds');
        $this->assertEquals(401, $this->client->getResponse()->getStatusCode());
    }

    public function testLater(): void
    {

        $crawler = $this->client->request('GET', '/api/v1/call/out/later/ksdlfjlkfds');
        $this->assertEquals(401, $this->client->getResponse()->getStatusCode());
    }
    public function testOccupied(): void
    {

        $crawler = $this->client->request('GET', '/api/v1/call/out/occupied/ksdlfjlkfds');
        $this->assertEquals(401, $this->client->getResponse()->getStatusCode());
    }
    public function testRinging(): void
    {

        $crawler = $this->client->request('GET', '/api/v1/call/out/ringing/ksdlfjlkfds');
        $this->assertEquals(401, $this->client->getResponse()->getStatusCode());
    }

    public function testDial(): void
    {
        $crawler = $this->client->request('GET', '/api/v1/call/out/dial/');
        $this->assertEquals(401, $this->client->getResponse()->getStatusCode());
    }
    public function testOnHoldPool(): void
    {
        $crawler = $this->client->request('GET', '/api/v1/call/out/on_hold/');
        $this->assertEquals(401, $this->client->getResponse()->getStatusCode());
    }
}
