#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
  path: /login/logout
  methods: GET

connect_keycloak_check:
  path:       /login/keycloak_login/check
  controller: App\Controller\LoginControllerKeycloak::check

when@prod:
  connect_keycloak_check:
    path: /login/keycloak_login/check
    controller: App\Controller\LoginControllerKeycloak::check

