#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
  path: /login/logout
  methods: GET

connect_keycloak_check:
  path:       /login/keycloak_login/check
  controller: App\Controller\LoginControllerKeycloak::check

when@prod:
  connect_keycloak_check:
    path: /login/keycloak_login/check
    controller: App\Controller\LoginControllerKeycloak::check
    schemes:    ['%app.scheme%']

catch_all:
  path: /{catchall}
  controller: App\Controller\CatchAllController::redirectToDefault
  requirements:
    catchall: .*
  condition: "env('ENABLE_CATCH_ALL') == 1"
  defaults:
    catchall: '' # Fallback-Wert für leere Anfragen