#!/bin/bash
systemctl stop jitsi-admin_messenger.service
systemctl stop jitsi-admin_websocket.service
systemctl disable jitsi-admin_websocket.service
systemctl disable jitsi-admin_websocket.service
a2dissite jitsiadmin
a2dissite jitsiadmin_ssl