# disables non-TLS listeners, only TLS-enabled clients will be able to connect
listeners.tcp = none

listeners.ssl.default = 5671

ssl_options.cacertfile = /ca_certificate.pem
ssl_options.certfile   = /server_certificate.pem
ssl_options.keyfile    = /server_key.pem

# Require client certificates (mutual TLS)
ssl_options.verify = verify_peer
ssl_options.fail_if_no_peer_cert = true
