name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
#      - name: Prepare Symfony
#        run: cp .env.sample .env.local
      - name: Write Version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "laF_version=2.0.0-dev"
          replace: "laF_version=GITHUB.${{github.run_number}}"
          regex: false
          include: ".env.local"
      - name: INstall PHP Dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          php_extensions: ldap xsl zip
      - name: Install NPM Packages
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build the Appication JS ans CSS
        run: |
          npm install
          npm run build

      - name: Remove node_module Directory
        run: rm -rf node_modules/

      - name: Build Websocket
        working-directory: nodejs/
        run: npm install
      - name: zip Application
        run: zip -r release.zip ./*

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: application_GITHUB_CI_${{github.run_number}}.zip
          path: release.zip

      - name: Upload Artifact Websocket
        uses: actions/upload-artifact@v3
        with:
          name: websocket_GITHUB_CI_${{github.run_number}}.zip
          path: nodejs/
    # ... then your own project steps ...