name: Check Changelog
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - master
      - development
jobs:
  build:
    name: Check Actions
    runs-on: ubuntu-latest
    steps:
      - name: Update Repository
        uses: actions/checkout@v1

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: error
          path: ./RELEASE_NOTE.md
