name: Development Pipeline

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    # region declare_service
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
    # endregion declare_service
    steps:
      # region git_pull
      - name: Pull current commit
        uses: actions/checkout@v3
      # endregion git_pull
      # region update_php_version
      - name: Update PHP Version and tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      # endregion update_php_version
      # region setup
      # region mysql_start
      - name: MySQL start
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql --user=root --password=root -e "CREATE USER 'jitsiadmintest'@'localhost' IDENTIFIED  BY 'password';"
          sudo mysql --user=root --password=root -e "GRANT ALL PRIVILEGES ON jitsiadmintest.* TO 'jitsiadmintest'@'localhost';"
          sudo mysql --user=root --password=root -e "FLUSH PRIVILEGES;"
      # endregion mysql_start
      # region composer_install
      - name: Composer Install
        run: composer install
      # endregion composer_install
      # region npm_install
      - name: NPM Install
        run: |
          npm install
          npm run build
      # endregion npm_install
      # endregion setup
      # region test
      # region phpunit
      - name: Run PHP-Unit tests
        run: php composer.phar test
      # endregion phpunit
      # endregion test