name: Create Pre-Release
env:
  GITHUB_TOKEN: ${{ secrets.token }}

on:
  push:
    branches:
      - feature/development
      - unstable/*

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: paulhatch/semantic-version@v5.0.2
        id: version
        with:
          tag_prefix: ""
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          change_path: .
          version_format: "${major}.${minor}.${patch}"

  artifact:
    uses: ./.github/workflows/task-artifact.yml

  test:
    uses: ./.github/workflows/task-test.yml
    needs:
      - artifact

  release:
    needs:
      - artifact
      - version
      - test
    uses: ./.github/workflows/task-release.yml
    with:
      version: ${{ needs.version.outputs.version }}
      prerelease: true

  upload_dockerhub_main:
    needs:
      - version
      - test
    uses: ./.github/workflows/task-upload-docker-hub.yml
    with:
      reponame: 'h2invent/jitsi-admin-main'
      dockerfile_path: './Dockerfile'
      directory: '.'
      version: "h2invent/jitsi-admin-main:dev-ci-unstable-${{github.run_number}}"
    secrets:
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}

  upload_dockerhub_websocket:
    needs:
      - version
      - test
    uses: ./.github/workflows/task-upload-docker-hub.yml
    with:
      reponame: 'h2invent/jitsi-admin-websocket'
      dockerfile_path: './nodejs/Dockerfile'
      directory: './nodejs'
      version: "h2invent/jitsi-admin-websocket:dev-ci-unstable-${{github.run_number}}"
    secrets:
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
