name: Create Release Build

permissions:
  contents: write
  packages: write

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, closed]
    branches:
      - "release/**"
  workflow_dispatch:
    inputs:
      branch:
        description: "release/X.Y Branch, für den ein Preview-Tag gebaut werden soll"
        required: true

jobs:
  version:
    uses: ./.github/workflows/task-version.yml

  artifact:
    uses: ./.github/workflows/task-artifact.yml

  test:
    uses: ./.github/workflows/task-test.yml
    needs:
      - artifact

  docker_core:
    needs:
      - version
      - test
    uses: ./.github/workflows/task-upload-docker-hub.yml
    with:
      registry: reg.h2-invent.com
      dockerfile_path: './Dockerfile-prod'
      directory: '.'
      version: ${{ needs.version.outputs.version }}
      tags: reg.h2-invent.com/meetling/core:${{ needs.version.outputs.version }}
    secrets:
      dockerhub_password: ${{ secrets.HARBOR_PUSH_PASSWORD }}
      dockerhub_username: ${{ secrets.HARBOR_PUSH_USERNAME }}

  docker_websocket:
    needs:
      - version
      - test
    uses: ./.github/workflows/task-upload-docker-hub.yml
    with:
      registry: reg.h2-invent.com
      dockerfile_path: './nodejs/Dockerfile-prod'
      directory: './nodejs'
      version: ${{ needs.version.outputs.version }}
      tags: reg.h2-invent.com/meetling/websocket:${{ needs.version.outputs.version }}
    secrets:
      dockerhub_password: ${{ secrets.HARBOR_PUSH_PASSWORD }}
      dockerhub_username: ${{ secrets.HARBOR_PUSH_USERNAME }}
