name: Test Pipeline

on: [push]

jobs:
  wiki:
    uses: ./.github/workflows/task-wiki-release.yml
    with:
      version: 0.0.0

  artifact:
    uses: ./.github/workflows/task-artifact.yml

  test:
    uses: ./.github/workflows/task-test.yml
    needs:
      - artifact
