name: Create Pre-Release
env:
  GITHUB_TOKEN: ${{ secrets.token }}

on:
  push:
    branches:
      - feature/development
      - unstable/*
      - hotfix/*

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: paulhatch/semantic-version@v5.0.2
        id: version
        with:
          tag_prefix: ""
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          change_path: .
          version_format: "${major}.${minor}.${patch}-${increment}"

  artifact:
    uses: ./.github/workflows/task-artifact.yml

  test:
    uses: ./.github/workflows/task-test.yml
    needs:
      - artifact

  release:
    needs:
      - artifact
      - version
      - test
    uses: ./.github/workflows/task-release.yml
    with:
      version: ${{ needs.version.outputs.version }}
      prerelease: true

  release_note:
    uses: ./.github/workflows/task-wiki-release.yml
    needs:
      - version
    with:
      version: ${{ needs.version.outputs.version }}

  dockerhub_application:
    needs:
      - version
      - test
    uses: ./.github/workflows/task-upload-docker-hub.yml
    with:
      reponame: 'h2invent/jitsi-admin-main'
      dockerfile_path: './Dockerfile'
      directory: '.'
      version: ${{ needs.version.outputs.version }}
      tags: h2invent/jitsi-admin-main:${{ needs.version.outputs.version }}
    secrets:
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}

  dockerhub_websocket:
    needs:
      - version
      - test
    uses: ./.github/workflows/task-upload-docker-hub.yml
    with:
      reponame: 'h2invent/jitsi-admin-websocket'
      dockerfile_path: './nodejs/Dockerfile'
      directory: './nodejs'
      version: ${{ needs.version.outputs.version }}
      tags: h2invent/jitsi-admin-websocket:${{ needs.version.outputs.version }}
    secrets:
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}

  docker_prod_application:
    needs:
      - version
      - test
    uses: ./.github/workflows/task-upload-docker-hub.yml
    with:
      reponame: 'git.h2-invent.com/meetling/application'
      registry: git.h2-invent.com
      dockerfile_path: './Dockerfile-prod'
      directory: '.'
      version: ${{ needs.version.outputs.version }}
      tags: git.h2-invent.com/meetling/application:${{ needs.version.outputs.version }}
    secrets:
      dockerhub_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      dockerhub_username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}

  docker_prod_websocket:
    needs:
      - version
      - test
    uses: ./.github/workflows/task-upload-docker-hub.yml
    with:
      reponame: 'git.h2-invent.com/meetling/websocket'
      registry: git.h2-invent.com
      dockerfile_path: './nodejs/Dockerfile-prod'
      directory: './nodejs'
      version: ${{ needs.version.outputs.version }}
      tags: git.h2-invent.com/meetling/websocket:${{ needs.version.outputs.version }}
    secrets:
      dockerhub_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      dockerhub_username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
