name: Test Pipeline

on: [push]

jobs:
  wiki:
    uses: ./.github/workflows/task-wiki-release.yml
    with:
      version: 1.2.8
      repo: h2-invent/jitsi-admin
    secrets:
      token: ${{ secrets.token }}

  artifact:
    uses: ./.github/workflows/task-artifact.yml

  test:
    uses: ./.github/workflows/task-test.yml
    needs:
      - artifact
