name: Create Release

env:
  GITHUB_TOKEN: ${{ secrets.token }}

on:
  push:
    branches:
      - main
      - master

jobs:
  version:
    uses: h2-invent/jitsi-admin/.github/workflows/task-version.yml@devops
  artifact:
    uses: h2-invent/jitsi-admin/.github/workflows/task-artifact.yml@devops

  create_release:
    needs:
      - version
      - artifact
    runs-on: ubuntu-latest
    outputs:
      create_release_output: ${{ steps.version.outputs.version }}
    steps:

      - uses: actions/download-artifact@v4
        with:
          name: artifact_${{github.run_number}}

      - run: unzip -qq artifact_${{github.run_number}}.zip -d artifact

      - name: Set laF_version in .env
        run: |
          sed -i 's/^laF_version=.*/laF_version=${{ needs.version.outputs.version_output }}/' artifact/.env

      - name: Archive Release for application
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'application.zip'
          exclusions: '*.git* *.github* /*node_modules/* /*nodejs/* /*var/* .editorconfig'
          directory: artifact

      - name: Archive Release for websocket
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'websocket.zip'
          directory: artifact/nodejs

      - name: Create new Release with semantic-version tag
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          allowUpdates: true
          name: Release ${{ needs.version.outputs.version_output }}
          tag: ${{ needs.version.outputs.version_output }}
          artifacts: artifact/application.zip,artifact/nodejs/websocket.zip
          artifactContentType: application/zip
          bodyFile: RELEASE_NOTE.md

  upload_dockerhub_main:
    needs:
      - version
    uses: h2-invent/jitsi-admin/.github/workflows/task-upload-docker-hub.yml@devops
    with:
      reponame: 'h2invent/jitsi-admin-main'
      dockerfile_path: './Dockerfile'
      directory: '.'
      version: h2invent/jitsi-admin-main:latest,h2invent/jitsi-admin-main:${{ needs.version.outputs.version_output }}
    secrets:
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}

  upload_dockerhub_websocket:
    needs:
      - create_release
    uses: h2-invent/jitsi-admin/.github/workflows/task-upload-docker-hub.yml@devops
    with:
      reponame: 'h2invent/jitsi-admin-websocket'
      dockerfile_path: './nodejs/Dockerfile'
      directory: './nodejs'
      version: h2invent/jitsi-admin-websocket:latest,h2invent/jitsi-admin-websocket:${{ needs.version.outputs.version_output }}
    secrets:
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
