name: Define version

on:
  workflow_call:
    outputs:
      version:
        description: "Computed version"
        value: ${{ jobs.version.outputs.version }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Compute tag
        id: version
        uses: h2-invent/action-compute-tag@v2.2.0
        with:
          event-name: ${{ github.event_name }}
          base-ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.event.pull_request.base.ref }}
          head-ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.event.pull_request.head.ref }}
          pr-action: ${{ github.event.action }}
          pr-merged: ${{ github.event.pull_request.merged }}
