name: Wiki

on:
  workflow_call:
    inputs:
      repo:
        description: 'Clone Repo'
        default: true
        type: string
      version:
        description: 'release version'
        default: true
        type: string
    secrets:
      token:
        required: true

jobs:
  publish_release_notes:
    name: Publish Release Notes to Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Update Content from wiki
        run: |
          git clone https://${{ secrets.token }}@github.com/${{ inputs.repo }}.wiki.git
          cd ${{ inputs.repo }}.wiki
          wget -O Release_Notes/Release_Note_${{ inputs.version }}.md \
          https://raw.githubusercontent.com/${{ inputs.repo }}/refs/tags/${{ inputs.version }}/RELEASE_NOTE.md
          git config user.name 'H2 invent Release Bot'
          git config user.email 'support@h2-invent.com'
          git add .
          git commit -m "Update Release Note ${{ inputs.version }} in Wiki" 
          git push -f --set-upstream https://${{ secrets.token }}@github.com/${{ inputs.repo }}.wiki.git master
