name: Build Artifacts

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite:///%kernel.project_dir%/var/dummy.db
    steps:
      - uses: actions/checkout@v5

      - name: Update PHP Version and tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          ini-values: date.timezone ="Europe/Berlin"
          tools: composer:v2

       - name: Install NPM Packages
         uses: actions/setup-node@v5
         with:
           node-version: '22'

      - name: Run composer Install
        run: composer install

      - name: Warmup Symfony cache
        run: php bin/console cache:warmup

      - name: Install Node modules
        run: npm install

      - name: Build NPM Files
        run: npm run build

      - name: Remove node_modules
        run: rm -r node_modules

      - name: Install Node modules for the Websocket
        run: npm install
        working-directory: nodejs/

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r artifact_${{github.run_number}}.zip .

      - name: Upload articats
        uses: actions/upload-artifact@v5
        with:
          name: artifact_${{github.run_number}}
          path: artifact_${{github.run_number}}.zip
