name: Build Artifacts

on: workflow_call

jobs:

  run_php_unit_test:
    runs-on: ubuntu-latest
    
    # region declare_services
    services:
      mariadb:
        image: mariadb:10.11
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: jitsiadmintest
          MARIADB_USER: jitsiadmintest
          MARIADB_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "healthcheck.sh --connect --innodb_initialized"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    # endregion declare_services

    steps:
      # region load_artifact
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_${{github.run_number}}

      - name: Unzip Artifact
        run: unzip -qq artifact_${{github.run_number}}.zip -d .
      # endregion load_artifact
      # region test
      # region phpunit
      - name: Update PHP Version and tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ vars.PHP_VERSION }}
          ini-values: date.timezone ="Europe/Berlin"
          tools: composer:v2

      - name: Run php test
        run: composer test
      # endregion phpunit
      # endregion test
