name: Wiki

on:
  workflow_call:
    inputs:
      repo:
        description: 'Clone Repo'
        default: true
        type: string
      version:
        description: 'release version'
        default: true
        type: string
    secrets:
      token:
        required: true

jobs:
  publish_release_notes:
    name: Publish Release Notes to Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Changelog check
        uses: Zomzog/changelog-checker@v1.2.0
        with:
          fileName: RELEASE_NOTE.md
          noChangelogLabel: my custom label # default `no changelog`
          checkNotification: Simple # default `Detailed`
          
      - name: Checkout wiki code
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          ref: master
          path: wiki

      - name: Update Content from wiki
        run: |
          cd wiki
          cat <<EOF > Release-Notes/notification_${{ inputs.version }}.json
            {
              "text": "A new Release of Jitsi Admin has been installed.<br>
                Checkout more information about this release in the 
                <a href='https://raw.githubusercontent.com/wiki/${{ inputs.repo }}/Release-Notes/Release_Note_${{ inputs.version }}.md'>
                Release Notes
                </a>",
              "head": "New Release ${{ inputs.version }} installed",
              "type": "info",
              "identifier": "${{ inputs.version }}"
            }
          ]
          EOF
          wget -O Release-Notes/Release_Note_${{ inputs.version }}.md \
          https://raw.githubusercontent.com/${{ inputs.repo }}/refs/tags/${{ inputs.version }}/RELEASE_NOTE.md
          git config user.name 'H2 invent Release Bot'
          git config user.email 'support@h2-invent.com'
          git add .
          git commit -m "Update Release Note ${{ inputs.version }} in Wiki" 
          git push
