name: Build Artifacts

on: workflow_call

jobs:

  run_php_unit_test:
    runs-on: ubuntu-latest
    
    # region declare_services
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: jitsiadmintest
          MYSQL_USER: jitsiadmintest
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
    # endregion declare_services
    
    steps:
      - name: Update PHP Version and tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ vars.PHP_VERSION }}
          ini-values: date.timezone ="Europe/Berlin"
      # endregion mysql_start
      # region load_artifact
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact_${{github.run_number}}

      - name: Unzip Artifact
        run: unzip -qq artifact_${{github.run_number}}.zip -d .
      # endregion load_artifact
      # region test
      # region phpunit
      - name: Run database migrations
        run: |
          sleep 30  # Allow some time for the MySQL service to be fully up and running
          php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Run php test
        run: php composer.phar test
      # endregion phpunit
      # endregion test
