name: Build Artifacts

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install PHP Dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ vars.PHP_VERSION }}
          php_extensions: ldap xsl zip

      - name: Install NPM Packages
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - run: npm install
      - run: npm run build
      - run: rm -r node_modules

      - name: Build JS for the Websocket
        working-directory: nodejs/
        run: npm install

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r artifact_${{github.run_number}}.zip .

      - name: Upload articats
        uses: actions/upload-artifact@v3
        with:
          name: artifact_${{github.run_number}}
          path: artifact_${{github.run_number}}.zip
