name: Build Artifacts

on: workflow_call

jobs:

  run_php_unit_test:
    runs-on: ubuntu-latest
    
    # region declare_services
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
    # endregion declare_services
    
    steps:
      # region mysql_start
      - name: MySQL start
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql --user=root --password=root -e "CREATE USER 'jitsiadmintest'@'localhost' IDENTIFIED  BY 'password';"
          sudo mysql --user=root --password=root -e "GRANT ALL PRIVILEGES ON jitsiadmintest.* TO 'jitsiadmintest'@'localhost';"
          sudo mysql --user=root --password=root -e "FLUSH PRIVILEGES;"
      # endregion mysql_start
      # region load_artifact
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact_${{github.run_number}}
      - name: Unzip Artifact
        run: unzip -qq artifact_${{github.run_number}}.zip -d .
      - name: List directory
        run: ls -ls
      # endregion load_artifact
      # region test
      # region phpunit
      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          configuration: "./phpunit.xml.dist"
          version: 9
          memory_limit: "1024M"
          testsuite: "Development"
          php_version: ${{ vars.PHP_VERSION }}
          php_extensions: ldap xsl zip intl pdo_mysql mysqli
      # endregion phpunit
      # endregion test
