name: Build Artifacts

on: workflow_call

jobs:

  run_php_unit_test:
    runs-on: ubuntu-latest
    
    # region declare_services
    services:
      mysql:
        image: mariadb:10.11
        env:
          MARIADB_ROOT_PASSWORD: root
    # endregion declare_services

    steps:
      # region mariadb_start
      - name: MariaDB start
        run: |
          sudo /etc/init.d/mysql start
          sudo mariadb --user=root --password=root -e "CREATE USER 'jitsiadmintest'@'localhost' IDENTIFIED  BY 'password';"
          sudo mariadb --user=root --password=root -e "GRANT ALL PRIVILEGES ON jitsiadmintest.* TO 'jitsiadmintest'@'localhost';"
          sudo mariadb --user=root --password=root -e "FLUSH PRIVILEGES;"
      # endregion mariadb_start
      # region load_artifact
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_${{github.run_number}}

      - name: Unzip Artifact
        run: unzip -qq artifact_${{github.run_number}}.zip -d .
      # endregion load_artifact
      # region test
      # region phpunit
      - name: Update PHP Version and tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ vars.PHP_VERSION }}
          ini-values: date.timezone ="Europe/Berlin"

      - name: Run php test
        run: php composer.phar test
      # endregion phpunit
      # endregion test
